<Workspace Version="1.3.3.4111" X="-24.1921889228336" Y="101.66554767521" zoom="0.996788271643059" ScaleFactor="1" Name="DuplicateTagCheck" Description="Checks Views for Duplicate Tags" ID="877741d8-1734-4905-a115-1b2fb7b3225a" Category="AKP Tools.Rebar">
  <NamespaceResolutionMap>
    <ClassMap partialName="DSCore.Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="d6492aa9-3f45-4f45-8004-baf0f3cdff8c" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1195.95801218097" y="662.374012323956" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="DSCore.Color.ByARGB(255,255,0,0);" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6417a744-13a6-4648-8807-5d021c9db6cf" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.OverrideColorInView" x="1597.95801218097" y="567.160678990623" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.OverrideColorInView@DSCore.Color">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.Logic.If guid="37c4b3a7-dff9-438e-82df-0e995558ffcc" type="CoreNodeModels.Logic.If" nickname="If" x="1195.95801218097" y="502.160678990623" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </CoreNodeModels.Logic.If>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="35ce914a-79b8-4faf-af9f-11f66023fb5b" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1091.4276626703" y="578.992038073415" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;&quot;;" ShouldFocus="false" />
    <CoreNodeModels.Logic.If guid="8bc67183-e929-4a25-9d60-74804848e549" type="CoreNodeModels.Logic.If" nickname="If" x="1223.16856461906" y="1.12831960170092" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </CoreNodeModels.Logic.If>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e1d053d9-c704-4dd8-bd1a-52b3577d89fe" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1118.63821510839" y="77.959678684492" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;&quot;;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="067b511a-7118-4e8f-b53a-b45f2d12f84a" type="PythonNodeModels.PythonNode" nickname="Select Elements" x="1390.43327523708" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
import System.Object
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

input = UnwrapElement(IN[0])
elt=[]
for i in input:
	elt.append(i.Id)

collection = List[ElementId](elt)

uidoc.Selection.SetElementIds(collection)

OUT = input</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="04c3effc-2d2c-436d-9140-4c58a27aaf58" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="426.430758302774" y="286.09106695839" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="Flatten(x);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="740b0aad-55f6-4386-a84c-55d5ffb5ee27" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="279.293547343723" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

coll = FilteredElementCollector(doc,doc.ActiveView.Id)

tagsinview = coll.OfCategory(BuiltInCategory.OST_RebarTags).ToElements()

elements = []

duptags = []

dupeles = []

dupdims = []

rebar = []


for t in tagsinview:

	id = t.TaggedLocalElementId
	element = doc.GetElement(id)
# if tag is a multi tag gets element id of dimension family then gets the rebar element assocaited with the dimension family and adds to list

	if element.GetType().ToString() == "Autodesk.Revit.DB.Dimension":
		uId = set([r.ElementId for r in element.References])
		
		for ui in uId:
			
			elements.append(ui)
	else:
# if tag not multi tag direclty adds rebar to list
			elements.append(element.Id)


for e in elements:

	
	y = elements.count(e)
	
	if y &gt; 1:

		dupeles.append(e)
		
	else:
	
		pass

for t in tagsinview:

	id = t.TaggedLocalElementId
	element = doc.GetElement(id)

	if element.GetType().ToString() == "Autodesk.Revit.DB.Dimension":
		rebarId = set([r.ElementId for r in element.References])
		
		for ids in rebarId:
		
			if ids in dupeles:
			
				duptags.append(t)	
				dupdims.append(element)
			
	else: 
		srebarId = set([element.Id])
		
		for ids in srebarId:
		
			if ids in dupeles:
			
				duptags.append(t)
		
for ele in dupeles:

	rebar.append(doc.GetElement(ele).ToDSType(True))
		

OUT = rebar,duptags,dupdims
			
			</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f38bc553-069b-47d2-a16e-c35b5401f846" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1891.95801218097" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8e63c76b-fbf5-4efa-aa4c-088a129f3669" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="719.957439159668" y="565.013990699197" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//changes color of duplicates&#xD;&#xA;ChangeColor:bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="232284a5-f063-4b12-96d7-6fce8cc72e10" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="793.246775862226" y="-31.6907395271106" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Selects elements in view&#xD;&#xA;SelectInView:bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d6492aa9-3f45-4f45-8004-baf0f3cdff8c" start_index="0" end="6417a744-13a6-4648-8807-5d021c9db6cf" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="37c4b3a7-dff9-438e-82df-0e995558ffcc" start_index="0" end="6417a744-13a6-4648-8807-5d021c9db6cf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="35ce914a-79b8-4faf-af9f-11f66023fb5b" start_index="0" end="37c4b3a7-dff9-438e-82df-0e995558ffcc" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8bc67183-e929-4a25-9d60-74804848e549" start_index="0" end="067b511a-7118-4e8f-b53a-b45f2d12f84a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e1d053d9-c704-4dd8-bd1a-52b3577d89fe" start_index="0" end="8bc67183-e929-4a25-9d60-74804848e549" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="04c3effc-2d2c-436d-9140-4c58a27aaf58" start_index="0" end="37c4b3a7-dff9-438e-82df-0e995558ffcc" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="04c3effc-2d2c-436d-9140-4c58a27aaf58" start_index="0" end="8bc67183-e929-4a25-9d60-74804848e549" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="04c3effc-2d2c-436d-9140-4c58a27aaf58" start_index="0" end="f38bc553-069b-47d2-a16e-c35b5401f846" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="740b0aad-55f6-4386-a84c-55d5ffb5ee27" start_index="0" end="04c3effc-2d2c-436d-9140-4c58a27aaf58" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8e63c76b-fbf5-4efa-aa4c-088a129f3669" start_index="0" end="37c4b3a7-dff9-438e-82df-0e995558ffcc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="232284a5-f063-4b12-96d7-6fce8cc72e10" start_index="0" end="8bc67183-e929-4a25-9d60-74804848e549" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="88477079-b450-49a5-a712-b137b932fe7b" annotationText="Change Color" left="1081.4276626703" top="456.160678990623" width="745.53034951067" height="274.213333333333" fontSize="30" InitialTop="502.160678990623" InitialHeight="417.010425299049" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="d6492aa9-3f45-4f45-8004-baf0f3cdff8c" />
      <Models ModelGuid="6417a744-13a6-4648-8807-5d021c9db6cf" />
      <Models ModelGuid="37c4b3a7-dff9-438e-82df-0e995558ffcc" />
      <Models ModelGuid="35ce914a-79b8-4faf-af9f-11f66023fb5b" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="afff8857-b83a-4516-96c0-3fc4ac76a84b" annotationText="Select Elements" left="1108.63821510839" top="-46" width="415.79506012869" height="191.959678684492" fontSize="30" InitialTop="0" InitialHeight="200.959678684491" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="8bc67183-e929-4a25-9d60-74804848e549" />
      <Models ModelGuid="e1d053d9-c704-4dd8-bd1a-52b3577d89fe" />
      <Models ModelGuid="067b511a-7118-4e8f-b53a-b45f2d12f84a" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="5e297498-80c4-44e2-ba7b-c21e4bfa7fae" annotationText="1.Check Duplicates" left="240" top="197.293547343723" width="147.89" height="176" fontSize="30" InitialTop="279.293547343723" InitialHeight="123" TextblockHeight="72" backgrouund="#FFFFAA45">
      <Models ModelGuid="740b0aad-55f6-4386-a84c-55d5ffb5ee27" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
</Workspace>