<Workspace Version="1.3.2.2480" X="65.7107664840266" Y="220.863154194374" zoom="0.888789228297156" ScaleFactor="1" Name="ElementIsPinnedInView" Description="Returns lists For Pinned and Unpinned Elements in ActiveView" ID="e7a1384c-7563-4d05-8d65-f4343c032728" Category="AKP Tools.General">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0443bd17-73ac-47bc-a0cf-c51e08109ccc" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="449.584973235169" y="121.988508536546" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Notpinned[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="7c1b3a78-4e81-4928-90f3-659016eaac4d" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="446.276691116986" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Pinned[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="9a1f823f-1c2a-4e80-8539-775524a8946b" type="PythonNodeModels.PythonNode" nickname="All Elements in View" x="250" y="46.512456829154" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

coll = FilteredElementCollector(doc,doc.ActiveView.Id)

elementsinview = coll.WhereElementIsNotElementType().ToElements()

check = IN[0]

ispinned = []

pinned = []

notpinned = []

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)



if check == True:

	for element in elementsinview:			
			
		if element.Pinned == True:

			pinned.append(element)
		
		else:
		
			notpinned.append(element)
	
else:

	null

TransactionManager.Instance.TransactionTaskDone()



OUT=pinned,notpinned</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="8b89601c-e485-4855-97cb-54ef7f30b447" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="722.5" y="-5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="PinnedElements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="737082de-ab70-4b50-9933-e0bd99440709" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="716.5" y="142" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="UnpinnedElements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4fd00867-d50e-4318-acc5-cd466e2e5117" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-3.34811480872958" y="7.78138997627374" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Check:bool=false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="0443bd17-73ac-47bc-a0cf-c51e08109ccc" start_index="0" end="737082de-ab70-4b50-9933-e0bd99440709" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7c1b3a78-4e81-4928-90f3-659016eaac4d" start_index="0" end="8b89601c-e485-4855-97cb-54ef7f30b447" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9a1f823f-1c2a-4e80-8539-775524a8946b" start_index="0" end="7c1b3a78-4e81-4928-90f3-659016eaac4d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9a1f823f-1c2a-4e80-8539-775524a8946b" start_index="0" end="0443bd17-73ac-47bc-a0cf-c51e08109ccc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4fd00867-d50e-4318-acc5-cd466e2e5117" start_index="0" end="9a1f823f-1c2a-4e80-8539-775524a8946b" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>